version: 2.1

orbs:
  android: circleci/android@0.2.1
            
jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: create AVD
          command: sdkmanager "system-images;android-29;google_apis;x86_64" && echo "no" | avdmanager --verbose create avd --force --name "Pixel_3a_API_29" --package "system-images;android-29;google_apis;x86_64"
      - run:
          name: start AVD
          command: emulator @Pixel_3a_API_29 -no-window -no-audio
          background: true
      - run:
          name: wait for emulator
          command: adb wait-for-device shell 'while [[ -z $(getprop dev.bootcomplete) ]]; do sleep 1; done;'
      - run:
          name: Build
          command: ./gradlew build
      - run: 
          name: Verification - ConnectedCheck
          command: ./gradlew connectedCheck --stacktrace
      - run:
          name: test
          command: ./gradlew test --stacktrace