version: 2.1

orbs:
  android: circleci/android@0.2.1
            
jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: create AVD
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: start AVD
          command: emulator test -no-window -no-audio
          background: true
      - run:
          name: wait for emulator
          command: adb wait-for-device shell 'while [[ -z $(getprop dev.bootcomplete) ]]; do sleep 1; done;'
      - run:
          name: Build
          command: ./gradlew build
      - run: 
          name: Verification - ConnectedCheck
          command: ./gradlew connectedCheck --stacktrace
      - run:
          name: test
          command: ./gradlew test --stacktrace